sudo: required
language: bash
before_install: |
  curl -Ls https://convox.com/install/linux.zip > /tmp/convox.zip &&\
  sudo unzip /tmp/convox.zip -d /usr/local/bin
after_success:
  - convox deploy --app convoxapp --rack nongod/convoxrack
notifications:
  slack: 104corp:IYsPMQMlzQSNSvBU9a1JM21h
    on_success: always
    on_failure: always
